- name: Evaluate {{ snapshot_operator_project }} namespace if not exists
  k8s:
    api_key: '{{ token }}'
    host: '{{ server }}'
    validate_certs: '{{ verify_tls }}'
    api_version: v1
    kind: Namespace
    name: '{{ snapshot_operator_project }}'
    state: present

- name: Evaluate CatalogSource for Operator Snapshot
  k8s:
    api_key: '{{ token }}'
    host: '{{ server }}'
    validate_certs: '{{ verify_tls }}'
    state: present
    resource_definition: "{{ lookup('template', 'snapshot-catalogsource.yaml.j2') }}"
