- name: Evaluate {{backend_project }} namespace
  k8s:
    api_key: '{{ token }}'
    host: '{{ server }}'
    validate_certs: '{{ verify_tls }}'
    api_version: v1
    kind: Namespace
    name: '{{ backend_project }}'
    state: present

- name: Create Backend Database
  k8s:
    api_key: '{{ token }}'
    host: '{{ server }}'
    validate_certs: '{{ verify_tls }}'
    state: present
    namespace: '{{ backend_project }}'
    resource_definition: "{{ lookup('template', 'postgres-template.yml') }}"
    vars:
      POSTGRESQL_USER: dbuser
      POSTGRESQL_PASSWORD: password
      POSTGRESQL_DATABASE: sampledb
      POSTGRESQL_VERSION: latest

- name: Create Location API service
  k8s:
    api_key: '{{ token }}'
    host: '{{ server }}'
    validate_certs: '{{ verify_tls }}'
    state: present
    namespace: '{{ backend_project }}'
    resource_definition: "{{ lookup('template', 'location-service-temlate.yml') }}"
    vars:
      POSTGRESQL_USER: dbuser
      POSTGRESQL_PASSWORD: password
      POSTGRESQL_DATABASE: sampledb
      POSTGRESQL_VERSION: latest
