- name: Evaluate {{backend_project }} namespace
  k8s:
    api_key: '{{ token }}'
    host: '{{ server }}'
    validate_certs: '{{ verify_tls }}'
    api_version: v1
    kind: Namespace
    name: '{{ backend_project }}'
    state: present

- name: Create Backend Database
  k8s:
    api_key: '{{ token }}'
    host: '{{ server }}'
    validate_certs: '{{ verify_tls }}'
    state: present
    namespace: '{{ backend_project }}'
    resource_definition: "{{ lookup('template', 'postgres-template.yml') }}"

- name: Create Location API service
  k8s:
    api_key: '{{ token }}'
    host: '{{ server }}'
    validate_certs: '{{ verify_tls }}'
    state: present
    namespace: '{{ backend_project }}'
    resource_definition: "{{ lookup('template', 'location-service-template.yml') }}"
