#TODO transform this into URI call
POST https://api.cluster-h5rjq.h5rjq.sandbox915.opentlc.com:6443/apis/image.openshift.io/v1/namespaces/openshift/imagestreamimports
Request Headers:
 User-Agent: oc/4.9.0 (linux/amd64) kubernetes/96e95ce
 Accept: application/json, */*
 Content-Type: application/json
 Authorization: Bearer <masked>
