:walkthrough: Testing the International Inc. Locations page using our newly authenticated locations API
:3scale-url: https://www.3scale.net/
:3scale-admin-url: https://{user-username}-admin.{openshift-app-host}/p/login
:3scale-dev-portal-url: https://{user-username}.{openshift-app-host}/
:sso-url: https://keycloak-sso.{openshift-app-host}/auth/admin/{user-username}-realm/console
:openshift-url: {openshift-host}
:user-password: openshift

ifdef::env-github[]
endif::[]

[id='testing-web-app']
= Lab 7 - Deploying Apicast Using the Operator

Learn how to deploy a self managed instance of Apicast.

Audience:  Developers, Architects and Operations team

*Overview*



*Why Red Hat?*

Applications can be built from many technologies. In this case we use a simple web application, but a wide range of Red Hat and non-Red Hat technologies could be used.

*Credentials:*

Your username is: `{user-username}` +
Your password is: `{user-password}`

[type=walkthroughResource]
.OpenShift Console
****
* link:{openshift-url}[Console, window="_blank"]
****

[type=walkthroughResource]
.Red Hat SSO Console
****
* link:{sso-url}[Console, window="_blank"]
****

[time=5]
[id="update-openshift"]
== TBD


----
token=b8720a280c971656b07b474a84555214d8dcbc2b2ec80c09cd8c84e4269f7809
threescale_url=user1-admin.apps.cluster-qsfdq.qsfdq.sandbox1327.opentlc.com

oc create secret generic gateway-secret --from-literal=AdminPortalURL=https://$token@$threescale_url

https://05f8d3f71b76c5c95b8d05c24e8bca8a@user1-admin.apps.cluster-qsfdq.qsfdq.sandbox1327.opentlc.com/
----


  adminPortalCredentialsRef:
    name: gateway-secret
  deploymentEnvironment: Production
  exposedHost:
    host: prod-user1.apps.cluster-qsfdq.qsfdq.sandbox1327.opentlc.com
  logLevel: debug
  replicas: 1
