- name: Evaluate APIcast Subscription
  k8s:
    api_key: '{{ token }}'
    host: '{{ server }}'
    validate_certs: '{{ verify_tls }}'
    state: present
    kind: Subscription
    api_version: operators.coreos.com/v1alpha1
    namespace: openshift-operators
    definition:
      metadata:
        name: apicast-operator
      spec:
        channel: threescale-2.12
        installPlanApproval: Automatic
        name: apicast-operator
        source: redhat-operators
        sourceNamespace: openshift-marketplace

- name: Wait APIcast Operator to be Running
  k8s_info:
    api_key: '{{ token }}'
    host: '{{ server }}'
    validate_certs: '{{ verify_tls }}'
    api_version: v1
    kind: Pod
    namespace: openshift-operators
    label_selectors:
      - app = apicast
      - control-plane = controller-manager
    field_selectors:
      - status.phase=Running
  register: r_apicast_operator_pod
  retries: 120
  delay: 10
  until: r_apicast_operator_pod.resources | list | length == 1
